feat(docker): add tests to dockerfile

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -20,10 +20,16 @@ jobs:
       uses: docker/setup-buildx-action@v1
 
     - name: Build the Docker image
+      shell: bash
       run: |
-        export DOCKER_BUILDKIT=1
-        docker build -f build/final_image/Dockerfile -t vulnmapai:latest .
+        # fail if any bash syntax error
+        set -eEuo pipefail
 
-#    - name: Run Tests
-#      run: |
-#        docker run --rm --entrypoint=pytest --workdir=/app vulnmapai:latest -svv
+        export DOCKER_BUILDKIT=1
+
+        # with the new target, test the pytest works
+        docker build -f build/final_image/Dockerfile --target test -t test-vulmap-works:latest .
+        docker rmi test-vulmap-works:latest
+
+        # build the image aswell, in case more steps arise
+        docker build -f build/final_image/Dockerfile -t vulnmapai:latest .
